### ISSUE TITLE
IfNoValueTF missing {} around arg

### ISSUE THREAD

**Issue by fifty-six** [josephwright/josephwright.github.io#2]
The "From \newcommand to \NewDocumentCommand" article has an `\IfNoValueTF#1{...}{...}` which has a non-braced `#1`.
 
I was reading [From \newcommand to \NewDocumentCommand](https://www.texdev.net/2010/05/23/from-newcommand-to-newdocumentcommand/) and the last example there uses `\IfNoValueTF#1{...}{...}`. After going through the post, I also saw the previous post in the footer ([Promoting XParse](https://www.texdev.net/2010/05/22/promoting-xparse/)) - which had linked to your implementation of a `\en` command for an epsilon with an optional argument. Within the thread, the user had some issues due to a lack of braces - so I think they should also be there for the one in the first article, though I'm not entirely sure. Sorry to bother with an older article but I figured it might save someone similar issues if I was still reading it at this time (and it's really helpful btw)

**Comment by josephwright** [comment]
I've checked the source and I don't see this: can you attach a screenshot?

**Comment by fifty-six** [comment]
![Screenshot_20221024-000754.jpg](https://user-images.githubusercontent.com/10470872/197446938-b3f40484-6392-488b-871b-90fdea425df5.jpg)

**Comment by josephwright** [comment]
I can see where the confusion might arise: that's `\IfBooleanTF`, which can only ever take a single token as the first argument, so doesn't need braces.

**Comment by fifty-six** [comment]
Ah ok mb
